# Options to make hugo output files
# 用于 Hugo 输出文档的设置
# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/outputs.toml

home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
