# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/params.zh-cn.toml
description = "CX无敌(✨音羽之梦🌙)的个人博客"
# keywords = ["Anime", "Vocaloid", "Java"]

# Footer config
# 页面底部信息配置
[footer]
  # Custom content (HTML format is supported)
  # 自定义内容 (支持 HTML 格式)
  custom = '<div>源码 - <a href="https://github.com/CXwudi/personal-blog-source" target="_blank" rel="noopener noreffer" title="/CXwudi/personal-blog-source" one-link-mark="yes"><i class="fab fa-github fa-fw"></i>GitHub</a></div>'
  # license info (HTML format is supported)
  # 许可协议信息 (支持 HTML 格式)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/deed.zh" target="_blank">CC BY 4.0</a>'

# Page config
# 文章页面配置
[page]
  # configure the link to report issue for the post
  # 配置提交错误的链接
  linkToReport = "https://github.com/CXwudi/personal-blog-source/discussions/new?category=content-issue-report&title=[问题]%20{title}&body=|属性|值|%0A|-|-|%0A|标题|{title}|%0A|链接|{url}|%0A|文件|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|%0A%0A请详细描述你的问题。%0A%0A感谢你的问题报告。"
  # "https://github.com/CXwudi/personal-blog-source/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|"
  # https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # https://gitlab.com/user/repo/-/issues/new?issue[title]=[bug]%20{title}&issue[description]=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://gitlab.com/user/repo/-/edit/main/{path}|
  # Comment config
  # 评论系统设置
  [page.comment]
    # Waline comment config (https://waline.js.org)
    # Waline 评论系统设置 (https://waline.js.org)
    [page.comment.waline]
      # The first two emoji packs are re-ordered as chinese may prefer tieba emoji than twitter/discord emoji
      # and the cdn used here is 渺软公益 CDN
      emoji = [ 
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Tieba-New', 
        'https://jsd.onmicrosoft.cn/gh/walinejs/emojis@1.1.0/tw-emoji',
        'https://jsd.onmicrosoft.cn/gh/walinejs/emojis@1.1.0/qq',
        'https://jsd.onmicrosoft.cn/gh/walinejs/emojis@1.1.0/weibo',
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/bilibilitv',
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Snow-Miku',
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Menhera-chan',
        ]
    
# Sponsor config
# 赞助设置
[sponsor]
  bio = "希望您喜欢这些内容。期待与你在下一篇文章中再见。"

# Search config
# 搜索配置
[search]
  # snippet length of the result
  # 结果内容片段长度
  snippetLength = 50