# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/params.toml

# website title
# 网站标题
# title = "✨Otowa no Yume🌙 Space" # not needed
# DoIt theme version
# DoIt 主题版本
# when using git submodule, this is pretty much useless
version = "main" 
# site default theme ("light", "dark", "black", "auto")
# 网站默认主题 ("light", "dark", "black", "auto")
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = "https://github.com/CXwudi/personal-blog-source"
# which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
# 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
# date format
# 日期格式
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/avater/avatar small.jpg"] # ["/images/avatar.webp"]
# enable PWA
# 开启 PWA 支持
enablePWA = false
# license information
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>'
# [Experimental] Bundle js
bundle = false
# [Experimental] cache remote images, more info: https://github.com/HEIGE-PCloud/DoIt/pull/860#issue-1574342372
# [试验性功能] 缓存图床图片，详情请见：https://github.com/HEIGE-PCloud/DoIt/pull/860#issue-1574342372
cacheRemoteImages = false
# [Experimental] generate image srcset attribute with hugo image processing feature.
# [试验性功能] 使用 hugo 自带的图片处理功能生成 srcset 属性
optimizeImages = false
# [Experimental] resize method for srcset attribute in optimizeImages, more info: https://gohugo.io/content-management/image-processing/#image-processing-options
# [实验性功能] optimizeImages 中 srcset 属性的缩放方法, 详情请见：https://gohugo.io/content-management/image-processing/#image-processing-options
srcsetSmallResizeMethod = "700x webp Lanczos q75"
srcsetDefaultResizeMethod = "1200x webp Lanczos q75"
srcsetLargeResizeMethod = "2000x webp Lanczos q75"

# Home page config
# 主页信息设置
[home]
  # amount of RSS pages
  # RSS 文章数目
  rss = 12
  # Home page profile
  # 主页个人信息
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    # Gravatar 邮箱，用于优先在主页显示的头像
    # is blocked by China
    gravatarEmail = ""
    # URL of avatar shown in home page
    # 主页显示头像的 URL
    avatarURL = "/avater/avatar small.jpg"
    # URL the avatar links to
    # 头像的链接指向的 URL
    avatarLinkURL = "https://linktr.ee/CXwudi"
    # title shown in home page (HTML format is supported)
    # 主页显示的网站标题 (支持 HTML 格式)
    # title = "" # use config.en.toml
    # subtitle shown in home page
    # 主页显示的网站副标题
    subtitle = "初音ミクへ、「何があっても、ずっとあなたのそばにいるよ。」"
    # whether to use typeit animation for subtitle
    # 是否为副标题显示打字机动画
    typeit = true
    # whether to show social links
    # 是否显示社交账号
    social = true
    # disclaimer (HTML format is supported)
    # 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # Home page posts
  # 主页文章列表
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    # 主页每页显示文章数量
    paginate = 7

# App icon config
# 应用图标配置
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
  # title = "DoIt"
  # whether to omit favicon resource links
  # 是否隐藏网站图标资源链接
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
  svgFavicon = ""
  # Safari mask icon color
  # Safari 图标颜色
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  # Windows v8-10 磁贴颜色
  tileColor = "#da532c"
  # Header config
  # 页面头部导航栏配置
[header]
  # desktop header mode ("fixed", "normal", "auto")
  # 桌面端导航栏模式 ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  # 移动端导航栏模式 ("fixed", "normal", "auto")
  mobileMode = "auto"
  # theme change mode ("switch", "select")
  # 主题切换模式 ("switch", "select")
  themeChangeMode = "select"
  # Header title config
  # 页面头部导航栏标题配置
  # [header.title] # this enable advanced setting for site title
  #   # URL of the LOGO
  #   # LOGO 的 URL
  #   logo = ""
  #   # title name
  #   # 标题名称
  #   name = ""
  #   # you can add extra information before the name (HTML format is supported), such as icons
  #   # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  #   pre = ""
  #   # you can add extra information after the name (HTML format is supported), such as icons
  #   # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  #   post = ""
  #   # whether to use typeit animation for title name
  #   # 是否为标题显示打字机动画
  #   typeit = true

# Footer config
# 页面底部信息配置
[footer]
  enable = true
  # custom = # in i18n
  # whether to show Hugo and theme info
  # 是否显示 Hugo 和主题信息
  hugo = true
  # whether to show copyright info
  # 是否显示版权信息
  copyright = true
  # whether to show the author
  # 是否显示作者
  author = true
  # site creation time
  # 网站创立年份
  since = 2021
  # ICP info only in China (HTML format is supported)
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp = ""
  # license = # in i18n



# TypeIt config
# TypeIt 配置
# [typeit] # customize the typeit animation
#   # typing speed between each step (measured in milliseconds)
#   # 每一步的打字速度 (单位是毫秒)
#   speed = 100
#   # blinking speed of the cursor (measured in milliseconds)
#   # 光标的闪烁速度 (单位是毫秒)
#   cursorSpeed = 1000
#   # character used for the cursor (HTML format is supported)
#   # 光标的字符 (支持 HTML 格式)
#   cursorChar = "|"
#   # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
#   # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
#   duration = -1

# Analytics config
# 网站分析配置
[analytics]
enable = true
  # Google Analytics
  [analytics.google]
    id = "G-SR92PDDP44" # this should be your measurement ID, not stream ID
    # whether to anonymize IP
    # 是否匿名化用户 IP
    anonymizeIP = true
  # Cloudflare Analytics
  [analytics.cloudflare]
    # so far it only works on one domain, here we set the vercel domain
    # https://developers.cloudflare.com/analytics/faq/web-analytics/#can-i-use-the-same-js-snippet-for-a-different-domain
    token = "8aad24ed3d12420f9aff029526c9a70f"

# 主页的社交信息设置
[social]
  [social.linktree]
    weight = 1
    id = "CXwudi"
    # using proxy will hit cross origin error, which will not show up the icon and some css
    # id = "/" # a hacky way to not let DoIt theme use default value when id is blank
    # prefix = "https://lktr-proxy.mikufancx.live/" # using my own cloudflare worker proxy to bypass GFW
  [social.Ko-Fi]
    weight = 2
    id = "cxwudi"
  [social.email]
    weight = 99
    id = "charleschen0502@gmail.com"
  [social.rss]
    weight = 100

# Section (all posts) page config
# Section (所有文章) 页面配置
[section] # must be sync with [list], except [recentlyUpdated]
  # special amount of posts in each section page
  # section 页面每页显示文章数量
  paginate = 20
  # date format (month and day)
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # amount of RSS pages
  # RSS 文章数目
  rss = 10
  # recently updated posts settings
  # 最近更新文章设置
  [section.recentlyUpdated]
    enable = true
    rss = true
    days = 40 # allow an extra 10 days
    maxCount = 15


# Page config
# 文章页面配置
[page]
  # whether to hide a page from home page
  # 是否在主页隐藏一篇文章
  hiddenFromHomePage = false
  # whether to hide a page from search results
  # 是否在搜索结果中隐藏一篇文章
  hiddenFromSearch = false
  # whether to enable twemoji
  # 是否使用 twemoji
  twemoji = false
  # whether to enable lightgallery
  # 是否使用 lightgallery
  lightgallery = false
  # whether to enable the ruby extended syntax
  # 是否使用 ruby 扩展语法
  ruby = true
  # whether to enable the fraction extended syntax
  # 是否使用 fraction 扩展语法
  fraction = true
  # whether to enable the fontawesome extended syntax
  # 是否使用 fontawesome 扩展语法
  fontawesome = false
  # whether to show link to Raw Markdown content of the content
  # 是否显示原始 Markdown 文档内容的链接
  linkToMarkdown = true
  # configure the link to view source the post
  # 配置文章原始文件的链接
  linkToSource = "https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}"
  # "https://github.com/user/repo/blob/main/{path}"
  # configure the link to edit the post
  # 配置编辑文章的链接
  linkToEdit = "https://github.com/CXwudi/personal-blog-source/edit/main/content/{path}"
  # https://github.com/user/repo/edit/main/{path}
  # https://gitlab.com/user/repo/-/edit/main/{path}
  # https://bitbucket.org/user/repo/src/main/{path}?mode=edit
  # linkToReport = # in i18n
  # 是否在 RSS 中显示全文内容
  rssFullText = true
  # Page style ("normal", "wide")
  # 页面样式 ("normal", "wide")
  # pageStyle = "normal"  # this setting is removed, see https://github.com/HEIGE-PCloud/DoIt/releases/tag/v0.4.0
  # whether to enable series navigation
  # 是否使用系列导航
  seriesNavigation = true
  # whether to enable last modified time
  # 是否启用最后修改时间
  enableLastMod = true
  # whether to enable word count
  # 是否启用字数统计
  enableWordCount = true
  # whether to enable reading time estimation
  # 是否启用阅读时间估计
  enableReadingTime = true
  # instant.page config
  [page.instantpage]
    enable = true
  # Display a message at the beginning of an article to warn the reader that its content might be outdated.
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [page.outdatedArticleReminder]
    enable = false
    # Display the reminder if the last modified time is more than 180 days ago.
    # 如果文章最后更新于这天数之前，显示提醒
    reminder = 180
    # Display warning if the last modified time is more than 365 days ago.
    # 如果文章最后更新于这天数之前，显示警告
    warning = 365
  # Table of the contents config
  # 目录配置
  [page.toc]
    # whether to enable the table of the contents
    # 是否使用目录
    enable = true
    # whether to keep the static table of the contents in front of the post
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    # 是否使侧边目录自动折叠展开
    auto = true
  # Code config
  # 代码配置
  [page.code]
    # the maximum number of lines of displayed code by default
    # 默认展开显示的代码行数
    maxShownLines = 20
  [page.table]
    # whether to enable sorting in the tables
    # 是否开启表格排序
    sort = true
  [page.header]
    # whether to enable auto header numbering
    # 是否开启标题自动编号
    [page.header.number]
      enable = true
      [page.header.number.format]
        h2 = "{h2}. {title}"
        h3 = "{h2}.{h3}. {title}"
        h4 = "{h2}.{h3}.{h4}. {title}"
        h5 = "{h2}.{h3}.{h4}.{h5}. {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6}. {title}"
  # KaTeX mathematical formulas config (KaTeX https://katex.org/)
  # KaTeX 数学公式配置 (KaTeX https://katex.org/)
  [page.math]
    enable = false
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    # 默认行内定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX extension mhchem
    # KaTeX 插件 mhchem
    mhchem = true
    # Use MathJax instead of KaTeX
    # 使用 MathJax 替代 KaTeX
    mathjax = false
  # Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
  # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
  [page.mapbox]
    # access token of Mapbox GL JS
    # Mapbox GL JS 的 access token
    accessToken = "" # disabled for now, need to resolve #25 first
    # style for the light theme
    # 浅色主题的地图样式
    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
    # style for the dark theme
    # 深色主题的地图样式
    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
    # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
    # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
    navigation = true
    # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
    # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
    geolocate = true
    # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
    # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
    scale = true
    # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
    # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
    fullscreen = true
  # Social share links in post page
  # 文章页面的分享信息设置
  [page.share]
    enable = true
    Baidu = false # is not available
    Blogger = false
    Buffer = false
    Digg = false
    Evernote = true
    Facebook = true
    Flipboard = false
    HackerNews = true
    Instapaper = false
    Line = true
    Linkedin = false
    Mix = false
    Myspace = false
    Odnoklassniki = false
    Pinterest = false
    Pocket = false
    Reddit = true
    Renren = false
    Skype = false
    Stumbleupon = false
    Telegram = true
    Trello = false
    Tumblr = false
    Twitter = true
    VK = false
    Weibo = true
    # Weixin API example: "https://tenapi.cn/qr/?txt="
    # https://docs.tenapi.cn/qrcode.html
    # https://www.free-api.com/doc/531
    # http://www.alapi.cn/api/view/72
    # OR self-hosted: https://github.com/yhf7952/QrCodeApi
    Weixin = "https://api.oick.cn/qrcode/api.php?size=130&text="
    Whatsapp = true
    Xing = false
    Mastodon = true
  # Comment config
  # 评论系统设置
  [page.comment]
    enable = true
    # Waline comment config (https://waline.js.org)
    # Waline 评论系统设置 (https://waline.js.org)
    [page.comment.waline]
      enable = true
      serverURL = "https://blog-waline.mikufancx.cyou"
      pageview = true
      comment = true
      # emoji = # in i18n
      meta = ['nick', 'mail', 'link']
      requiredMeta = ['nick', 'mail']
      login = 'enabled' # use 'force' when we want to force the user to login to avoid spam, but so far let's just use requiredMeta
      wordLimit = 800  # we decide to put this limit to not let long strings break any system
      pageSize = 12
      imageUploader = false # not allowing storing images in our database
      highlighter = true
      texRenderer = false
      # The DoIt theme handled the language
  # Page SEO config
  # 页面 SEO 配置
  [page.seo]
    # image URL
    # 图片 URL
    images = []
    # Publisher info
    # 出版者信息
    [page.seo.publisher]
      # name = # in i18n
      logoUrl = "/avater/avatar small.jpg"
  # Related content config
  # 相关文章推荐配置
  [page.related] # disable for now
    enable = false
    count = 5


# Sponsor config
# 赞助设置
[sponsor]
  enable = false # disable for now, instead use main page to link the donatin page
  # bio = # in i18n
  link = "https://ko-fi.com/cxwudi"
  # currently DoIt has a bug where this custom tag is not at the center. Report it if we need sponsor one day
  # custom = "<div style='display: flex; justify-content: center;'><a href='https://ko-fi.com/X7X56IIAQ' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a></div>"

# Search config
# 搜索配置
[search]
  enable = true
  # type of search engine ("algolia", "fuse")
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse" # to use algolia, we need to sync the search index to algolia, see https://github.com/HEIGE-PCloud/DoIt/blob/main/.github/workflows/update-algolia-search-index.yml
  # max index length of the chunked content
  # 文章内容最长索引长度
  contentLength = 4000
  # placeholder of the search bar
  # 搜索框的占位提示语
  placeholder = ""
  # max number of results length
  # 最大结果数目
  maxResultLength = 10
  # snippetLength = # in i18n
  # HTML tag name of the highlight part in results
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  # 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false

# List (category or tag) page config
# List (目录或标签) 页面配置
[list]  # must be sync with [section]
  # special amount of posts in each list page
  # list 页面每页显示文章数量
  paginate = 20
  # date format (month and day)
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # amount of RSS pages
  # RSS 文章数目
  rss = 10

# Site SEO config
# 网站 SEO 配置
[seo]
  # image URL
  # 图片 URL
  # image = "/images/Apple-Devices-Preview.png"
  # thumbnail URL
  # 缩略图 URL
  # thumbnailUrl = "/images/screenshot.png"
  # Google 搜索结果中网站备用名字
  # alternate site name in Google search result
  # https://developers.google.com/search/docs/appearance/site-names#alternative
  # alternateName = ["Hugo DoIt"]

# Cookie consent config
# Cookie 许可配置
[cookieconsent]
  enable = false
  # text strings used for Cookie consent banner
  # 用于 Cookie 许可横幅的文本字符串
  [cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# CDN config for third-party library files
# 第三方库文件的 CDN 设置
[cdn]
  # CDN data file name, disabled by default
  # ("jsdelivr.yml")
  # located in "themes/DoIt/assets/data/cdn/" directory
  # you can store your own data files in the same path under your project:
  # "assets/data/cdn/"
  # CDN 数据文件名称, 默认不启用
  # ("jsdelivr.yml")
  # 位于 "themes/DoIt/assets/data/cdn/" 目录
  # 可以在你的项目下相同路径存放你自己的数据文件:
  # "assets/data/cdn/"
  data = ""

# Compatibility config
# 兼容性设置
[compatibility]
  # whether to use Polyfill.io to be compatible with older browsers
  # 是否使用 Polyfill.io 来兼容旧式浏览器
  polyfill = false
  # whether to use object-fit-images to be compatible with older browsers
  # 是否使用 object-fit-images 来兼容旧式浏览器
  objectFit = false
