# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/params.zh-cn.toml
description = "CX无敌(✨音羽之梦🌙)的个人博客"
# keywords = ["Anime", "Vocaloid", "Java"]


# Footer config
# 页面底部信息配置
[footer]
  enable = true
  # Custom content (HTML format is supported)
  # 自定义内容 (支持 HTML 格式)
  custom = '<div>源码 - <a href="https://github.com/CXwudi/personal-blog-source" target="_blank" rel="noopener noreffer" title="/CXwudi/personal-blog-source" one-link-mark="yes"><i class="fab fa-github fa-fw"></i>GitHub</a></div>'
  # whether to show Hugo and theme info
  # 是否显示 Hugo 和主题信息
  hugo = true
  # whether to show copyright info
  # 是否显示版权信息
  copyright = true
  # whether to show the author
  # 是否显示作者
  author = true
  # site creation time
  # 网站创立年份
  since = 2021
  # ICP info only in China (HTML format is supported)
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp = ""
  # license info (HTML format is supported)
  # 许可协议信息 (支持 HTML 格式)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/deed.zh" target="_blank">CC BY 4.0</a>'

# Page config
# 文章页面配置
[page]
  # whether to hide a page from home page
  # 是否在主页隐藏一篇文章
  hiddenFromHomePage = false
  # whether to hide a page from search results
  # 是否在搜索结果中隐藏一篇文章
  hiddenFromSearch = false
  # whether to enable twemoji
  # 是否使用 twemoji
  twemoji = false
  # whether to enable lightgallery
  # 是否使用 lightgallery
  lightgallery = false
  # whether to enable the ruby extended syntax
  # 是否使用 ruby 扩展语法
  ruby = true
  # whether to enable the fraction extended syntax
  # 是否使用 fraction 扩展语法
  fraction = true
  # whether to enable the fontawesome extended syntax
  # 是否使用 fontawesome 扩展语法
  fontawesome = true
  # whether to show link to Raw Markdown content of the content
  # 是否显示原始 Markdown 文档内容的链接
  linkToMarkdown = true
  # configure the link to view source the post
  # 配置文章原始文件的链接
  linkToSource = "https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}"
  # "https://github.com/user/repo/blob/main/{path}"
  # configure the link to edit the post
  # 配置编辑文章的链接
  linkToEdit = "https://github.com/CXwudi/personal-blog-source/edit/main/content/{path}"
  # https://github.com/user/repo/edit/main/{path}
  # https://gitlab.com/user/repo/-/edit/main/{path}
  # https://bitbucket.org/user/repo/src/main/{path}?mode=edit
  # configure the link to report issue for the post
  # 配置提交错误的链接
  linkToReport = "https://github.com/CXwudi/personal-blog-source/discussions/new?title=[issue]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|%0A%0APlease%20choose%20the%20proper%20category%20and%20describe%20the%20problem%20in%20detail.%0A%0AThank%20you%20for%20reporting%20the%20issue."
  # "https://github.com/CXwudi/personal-blog-source/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|"
  # https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # https://gitlab.com/user/repo/-/issues/new?issue[title]=[bug]%20{title}&issue[description]=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://gitlab.com/user/repo/-/edit/main/{path}|
  # whether to show the full text content in RSS
  # 是否在 RSS 中显示全文内容
  rssFullText = true
  # Page style ("normal", "wide")
  # 页面样式 ("normal", "wide")
  pageStyle = "normal"
  # whether to enable series navigation
  # 是否使用系列导航
  seriesNavigation = true
  # Display a message at the beginning of an article to warn the reader that its content might be outdated.
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [page.outdatedArticleReminder]
    enable = false # let's make it false by default, we enable it explicitly on each article
    # Display the reminder if the last modified time is more than 180 days ago.
    # 如果文章最后更新于这天数之前，显示提醒
    reminder = 180
    # Display warning if the last modified time is more than 365 days ago.
    # 如果文章最后更新于这天数之前，显示警告
    warning = 365
  # Table of the contents config
  # 目录配置
  [page.toc]
    # whether to enable the table of the contents
    # 是否使用目录
    enable = true
    # whether to keep the static table of the contents in front of the post
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    # 是否使侧边目录自动折叠展开
    auto = true
  # Code config
  # 代码配置
  [page.code]
    # whether to show the copy button of the code block
    # 是否显示代码块的复制按钮
    copy = true
    # the maximum number of lines of displayed code by default
    # 默认展开显示的代码行数
    maxShownLines = 10
  [page.table]
    # whether to enable sorting in the tables
    # 是否开启表格排序
    sort = true
  [page.header]
    # whether to enable auto header numbering
    # 是否开启标题自动编号
    # [page.header.number]
    #   enable = true
    #   [page.header.number.format]
    #     h2 = "{h2}. {title}"
    #     h3 = "{h2}.{h3}. {title}"
    #     h4 = "{h2}.{h3}.{h4}. {title}"
    #     h5 = "{h2}.{h3}.{h4}.{h5}. {title}"
    #     h6 = "{h2}.{h3}.{h4}.{h5}.{h6}. {title}"
  [page.comment]
    enable = true
    [page.comment.waline]
      enable = true
      serverURL = "https://cxwudi-blog-waline.vercel.app"
      pageview = true
      comment = true
      # emojis from https://waline.js.org/guide/client/emoji.html#%E9%A2%84%E8%AE%BE
      # and https://github.com/GamerNoTitle/Valine-Magic
      # the coding link for the emoji from GameNoTitle/Valine-Magic is not working, hence using author's proxy
      # but we are unsure when would it break again. need to keep an eye on it
      emoji = [
        'https://cdn.bilicdn.tk/gh/GamerNoTitle/ValineCDN@master/Tieba-New', # re-ordered as chinese may prefer tieba emoji than twitter/discord emoji
        'https://unpkg.com/@waline/emojis@1.1.0/tw-emoji',
        'https://unpkg.com/@waline/emojis@1.1.0/qq',
        'https://unpkg.com/@waline/emojis@1.1.0/weibo',
        'https://cdn.bilicdn.tk/gh/GamerNoTitle/ValineCDN@master/Snow-Miku',
        'https://cdn.bilicdn.tk/gh/GamerNoTitle/ValineCDN@master/Menhera-chan',
        ]
      meta = ['nick', 'mail', 'link']
      requiredMeta = ['nick', 'mail']
      login = 'enabled' # use 'force' when we want to force the user to login to avoid spam, but so far let's just use requiredMeta
      wordLimit = 800  # we decide to put this limit to not let long strings break any system
      pageSize = 12
      imageUploader = false
      highlighter = true
      texRenderer = false
      # it looks like waline can now detect language automatically
  # Social share links in post page
  # 文章页面的分享信息设置
  [page.share]
    enable = true
    Baidu = false # is not available
    Blogger = false
    Buffer = false
    Digg = false
    Evernote = true
    Facebook = true
    Flipboard = false
    HackerNews = true
    Instapaper = false
    Line = true
    Linkedin = false
    Mix = false
    Myspace = false
    Odnoklassniki = false
    Pinterest = false
    Pocket = false
    Reddit = true
    Renren = false
    Skype = false
    Stumbleupon = false
    Telegram = true
    Trello = false
    Tumblr = false
    Twitter = true
    VK = false
    Weibo = true
    # Weixin API example: "https://tenapi.cn/qr/?txt="
    # https://docs.tenapi.cn/qrcode.html
    # https://www.free-api.com/doc/531
    # http://www.alapi.cn/api/view/72
    # OR self-hosted: https://github.com/yhf7952/QrCodeApi
    Weixin = "https://api.oick.cn/qrcode/api.php?size=130&text="
    Whatsapp = true
    Xing = false
  # Page SEO config
  # 页面 SEO 配置
  [page.seo]
    # image URL
    # 图片 URL
    images = []
    # Publisher info
    # 出版者信息
    [page.seo.publisher]
      name = "xxxx"
      logoUrl = "/avater/avatar 1 smaller file size.jpg"
  # Related content config
  # 相关文章推荐配置
  [page.related]
    enable = false
    count = 5
    
# Sponsor config
# 赞助设置
[sponsor]
  enable = false
  bio = "希望您喜欢这些内容。期待与你在下一篇文章中再见。"
  link = "https://ko-fi.com/mikufancx"
  custom = "<a href='https://ko-fi.com/mikufancx' target='_blank'><img height='54' style='border:0px;height:54px;' src='https://storage.ko-fi.com/cdn/brandasset/kofi_s_logo_nolabel.png' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>"

# Search config
# 搜索配置
[search]
  enable = true
  # type of search engine ("algolia", "fuse")
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  # 文章内容最长索引长度
  contentLength = 4000
  # placeholder of the search bar
  # 搜索框的占位提示语
  placeholder = ""
  # max number of results length
  # 最大结果数目
  maxResultLength = 10
  # snippet length of the result
  # 结果内容片段长度
  snippetLength = 50
  # HTML tag name of the highlight part in results
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  # 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [search.algolia]
    index = "blog_zh_cn"
    appID = "9346ZAKTV2"
    searchKey = "7fdbdab62ae2a2f171c8cbea19ac38d6"
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false