baseURL = "http://example.org/"
theme = "DoIt"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    weight = 1
    title = "✨Otowa no Yume🌙 Personal Site"  
    languageCode = "en"
    languageName = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "series"
        pre = ""
        post = ""
        name = "Series"
        url = "/series/"
        title = ""
        weight = 4
        # let's hide this until we got a second author to avoid confusion
      # [[languages.en.menu.main]] 
      #   identifier = "authors"
      #   pre = ""
      #   post = ""
      #   name = "Authors"
      #   url = "/authors/"
      #   title = ""
      #   weight = 5
      [[languages.en.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
        weight = 6
    [languages.en.params]
      # site description
      description = "CXwudi's (✨Otowa no Yume🌙) Personal Site"
      # site keywords
      keywords = ["Vocaloid", "Anime", "Java"]
      # Home page config
      [languages.en.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = "cx2010017@gmail.com"
          subtitle = "TODO: something to say"
          typeit = true
          social = true
      [languages.en.params.page.comment]
        enable = true
        [languages.en.params.page.comment.waline]
          enable = true
          serverURL = "https://waline-vercel-ijtw8zr98-cxwudi.vercel.app/"
          wordLimit = 0
          avatar = "mp"
          lang = "en"
          meta = ["nick", "mail", "link"]
          pageSize = 12
          visitor = true
          highlight = true
          requiredFields = []
          anonymous = false
      # Social share links in post page
      # 文章页面的分享信息设置
      [languages.en.params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = false
        Whatsapp = false
        Pinterest = false
        Tumblr = false
        HackerNews = false
        Reddit = true
        VK = false
        Buffer = false
        Xing = false
        Line = true
        Instapaper = false
        Pocket = false
        Digg = false
        Stumbleupon = false
        Flipboard = false
        Weibo = true
        Renren = false
        Myspace = false
        Blogger = false
        Baidu = false # is not available
        Odnoklassniki = false
        Evernote = true
        Skype = true
        Trello = false
        Mix = false

  [languages.zh-cn]
    weight = 2
    title = "✨音羽之梦🌙の个人博客"  
    # language code, CN only here
    languageCode = "zh-CN"
    languageName = "简体中文"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = true
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "所有文章"
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.zh-cn.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.zh-cn.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "分类"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.zh-cn.menu.main]]
        identifier = "series"
        pre = ""
        post = ""
        name = "系列"
        url = "/series/"
        title = ""
        weight = 4
      # [[languages.zh-cn.menu.main]]
      #   identifier = "authors"
      #   pre = ""
      #   post = ""
      #   name = "作者"
      #   url = "/authors/"
      #   title = ""
      #   weight = 5
      [[languages.zh-cn.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "关于"
        url = "/about/"
        title = ""
        weight = 6
    [languages.zh-cn.params]
      description = "✨音羽之梦🌙の个人博客"
      keywords = ["Anime", "Vocaloid", "Java"]
      [languages.zh-cn.params.home]
        rss = 10
        [languages.zh-cn.params.home.profile]
          enable = true
          gravatarEmail = "cx2010017@gmail.com"
          subtitle = "座右铭（TODO）"
          typeit = true
          social = true
      [languages.zh-cn.params.page.comment]
        enable = true
        [languages.zh-cn.params.page.comment.waline]
          enable = true
          serverURL = "https://waline-vercel-ijtw8zr98-cxwudi.vercel.app/"
          wordLimit = 0
          avatar = "mp"
          lang = "zh-cn"
          meta = ["nick", "mail", "link"]
          pageSize = 12
          visitor = true
          highlight = true
          requiredFields = []
          anonymous = false
      # Social share links in post page
      # 文章页面的分享信息设置
      [languages.zh-cn.params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = false
        Whatsapp = false
        Pinterest = false
        Tumblr = false
        HackerNews = false
        Reddit = true
        VK = false
        Buffer = false
        Xing = false
        Line = true
        Instapaper = false
        Pocket = false
        Digg = false
        Stumbleupon = false
        Flipboard = false
        Weibo = true
        Renren = false
        Myspace = false
        Blogger = false
        Baidu = false
        Odnoklassniki = false
        Evernote = true
        Skype = true
        Trello = false
        Mix = false

# if you want some setting go i18n, 
# then all settings in same or sub module of that setting must go i18n
# e.g. the commenting system, the share button

[author] # no needed and use DoIt's multi authors
  name = "CXwudi"
  email = "charleschen0502@gmail.com"
  link = "https://linktr.ee/CXwudi"

[Permalinks]
  posts = ":year:month/:filename"
  # posts = ":filename"

[params]
  version = "0.2.X"
  title = "CXwudi's All-in-one Personal Site"

# Analytics config
# 网站分析配置
[params.analytics]
enable = false
  # Google Analytics
  [params.analytics.google]
    id = ""
    # whether to anonymize IP
    # 是否匿名化用户 IP
    anonymizeIP = true
  # Fathom Analytics
  [params.analytics.fathom]
    id = ""
    # server url for your tracker if you're self hosting
    # 自行托管追踪器时的主机路径
    server = ""

# Footer config
# 页面底部信息配置
[params.footer]
  enable = true
  # Custom content (HTML format is supported)
  # 自定义内容 (支持 HTML 格式)
  custom = ''
  # whether to show Hugo and theme info
  # 是否显示 Hugo 和主题信息
  hugo = true
  # whether to show copyright info
  # 是否显示版权信息
  copyright = true
  # whether to show the author
  # 是否显示作者
  author = true
  # site creation time
  # 网站创立年份
  since = 2021
  # ICP info only in China (HTML format is supported)
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp = ""
  # license info (HTML format is supported)
  # 许可协议信息 (支持 HTML 格式)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Page config
# 文章页面配置
[params.page]
  # whether to enable the ruby extended syntax
  # 是否使用 ruby 扩展语法
  ruby = true
  # whether to enable the fraction extended syntax
  # 是否使用 fraction 扩展语法
  fraction = true
  # whether to enable the fontawesome extended syntax
  # 是否使用 fontawesome 扩展语法
  fontawesome = true
  # whether to show link to Raw Markdown content of the content
  # 是否显示原始 Markdown 文档内容的链接
  linkToMarkdown = true
  # whether to show the full text content in RSS
  # 是否在 RSS 中显示全文内容
  rssFullText = true
  # Page style ("normal", "wide")
  # 页面样式 ("normal", "wide")
  pageStyle = "wide"


# Header config
# 页面头部导航栏配置
[params.header]
  # theme change mode ("switch", "select")
  # 主题切换模式 ("switch", "select")
  themeChangeMode = "select"

[params.search] # copied from sample site
  enable = true
  type = "fuse"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false

# 主页的社交信息设置
[params.social]
  linktree = "CXwudi"
  Email = "charleschen0502@gmail.com"
  RSS = true

[privacy] # copied from sample site
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false 

[outputs] # copied from sample site
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[outputFormats.MarkDown] # copied from sample site, needed for MarkDown
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false
[mediaTypes] # copied from sample site, needed for mediaType "text/plain"
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options for taxonomies
# 用于分类的设置, 很重要
[taxonomies]
  author = "authors" # don't remove, can make clicking authors return 404
  category = "categories"
  tag = "tags"
  series = "series" # need it to make series works properly