version: '3.9'

services:
  hugo:
    image: hugo-devcontainer
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${HUGO_VERSION}
    volumes:
      - ..:/workspace/personal-blog
      - ~/.ssh:/home/vscode/.ssh
    ports:
      - 1313:1313
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
  
    