# This is a basic workflow to help you get started with Actions

name: Repo Mirroring

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "to-gitlab"
  to-gitlab:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@dev.s-ul.net:CXwudi/personal-blog-source.git
          ssh_private_key: ${{ secrets.GITLAB_PRIVATE_SSH_KEY }} # <-- use 'secrets' to pass credential information.
    
  # This workflow contains a single job called "to-coding"
  to-coding:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@e.coding.net:cxwudi/personl-blog-related/personal-blog-source.git
          ssh_private_key: ${{ secrets.GITLAB_PRIVATE_SSH_KEY }} # <-- use 'secrets' to pass credential information.

#       - uses: wangchucheng/git-repo-sync@v0.1.0
#         with:
#           # Such as https://github.com/wangchucheng/git-repo-sync.git
#           target-url: https://dev.s-ul.net/CXwudi/personal-blog-source
#           # Such as wangchucheng
#           target-username: CXwudi
#           # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
#           target-token: ${{ secrets.GITLAB_TOKEN }}
          
#       - uses: SvanBoxel/gitlab-mirror-and-ci-action@master
#         with:
#           args: "https://gitlab.com/CXwudi/personal-blog-source"
#         env:
#           GITLAB_HOSTNAME: "gitlab.com"
#           GITLAB_USERNAME: "CXwudi"
#           GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }} # Generate here: https://gitlab.com/profile/personal_access_tokens
#           GITLAB_PROJECT_ID: "30322428" # https://gitlab.com/<namespace>/<repository>/edit
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
